version: "3.9"

services:
  db:
    container_name: db
    image: mysql:8.0-oracle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ${DB_SQL_PASSWORD}
      MYSQL_USER: ${DB_SQL_USERNAME}
      MYSQL_DATABASE: ${DB_SQL_DBNAME}
      MYSQL_TCP_PORT: ${DB_SQL_INPORT}
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    ports:
      - ${DB_SQL_OUTPORT}:${DB_SQL_INPORT}

  app:
    depends_on:
      - db
    command: sh -c "pipenv install && python src/run_migrations.py && python src/__main__.py"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/app
    links:
      - db
    env_file: ./.env
    environment:
      - DB_SQL_HOST=db
    ports:
      - ${APP_PORT}:${APP_PORT}
